web:
    build: .
    volumes:
      - ./:/app
    ports:
      - 80:5000
    environment:
       - APP_SETTINGS=config.ProductionConfig
       - DATABASE_URL=sqlite:///example.db
#    command: python manage.py runserver -h 0.0.0.0
    command: python manage.py test
